apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-scheduler
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-scheduler-as-kube-scheduler
subjects:
  - kind: ServiceAccount
    name: k8s-scheduler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-scheduler-as-volume-scheduler
subjects:
  - kind: ServiceAccount
    name: k8s-scheduler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: k8s-scheduler
    app.kubernetes.io/version: 1.0.0
  name: k8s-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-scheduler
      app.kubernetes.io/version: 1.0.0
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-scheduler
        app.kubernetes.io/version: 1.0.0
    spec:
      serviceAccountName: k8s-scheduler
      containers:
        - name: k8s-scheduler
          image: golang:1.16-alpine
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
