apiVersion: v1
kind: ServiceAccount
metadata:
  name: aida-scheduler
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aida-scheduler-as-kube-scheduler
subjects:
  - kind: ServiceAccount
    name: aida-scheduler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aida-scheduler-as-volume-scheduler
subjects:
  - kind: ServiceAccount
    name: aida-scheduler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: aida-scheduler
    app.kubernetes.io/version: latest
  name: aida-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aida-scheduler
      app.kubernetes.io/version: latest
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aida-scheduler
        app.kubernetes.io/version: latest
    spec:
      serviceAccountName: aida-scheduler
      containers:
        - name: aida-scheduler
          image: docker.pkg.github.com/aida-dos/aida-scheduler:latest
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
